### ISSUE TITLE
Fix sqrt rendering

### ISSUE THREAD

**Issue by karino2** [karino2/kotlitex#43]
With PR #42, some strange horizontal line is drawn.
I don't know whether this is because of rendering side or RNode side.

Please try to support sqrt code more seriously and figure out why current rendering is strange.

Once it becomes clear that buildExpression is wrong, please assign this issue to me.

**Comment by karino2** [comment]
Try create new Path whenever it closed.
Do not fix the problem.

https://github.com/karino2/kotlitex/tree/trial_fix_sqrt_rendering

**Comment by karino2** [comment]
Seems rCubicTo render nothing.
Why?

**Comment by karino2** [comment]
Scaling option of mat.setRectToRect() at MathExpressionSpan seems wrong.
That cause scaling to collapse vertical axis, that's cause result rendering as just horizontal line.

I just put to FILL, this is clearly wrong, but easier to debug further. (#44)

**Comment by karino2** [comment]
I'm sure buildExpression side have some bug...

**Comment by karino2** [comment]
I found most of the reason.

1. too large horizontal line cause path drawing to ignore (even though you clip)
2. Fill is not good enough for even in investigation

Now I can draw almost correct path (though position is wrong).
I'll PR soon.

**Comment by karino2** [comment]
Current status:

![190_369_325](https://user-images.githubusercontent.com/1468643/52060688-12b78680-25b0-11e9-92b0-c358ad8343f6.png)

**Comment by kzys** [comment]
Okay. Let me take a look.

**Comment by kzys** [comment]
@karino2 Can you update dumpresult.txt with `\sqrt{3}`? I'm unsure how did you generate the txt file.

**Comment by karino2** [comment]
Done.
Also, I add how to create these dumps in the end of dumpresult.txt.
Here is excerpt.

```
# How to create these dumps

const katex = require('./dist/katex.js')
katex.renderToString('\\sqrt{3}')
```

**Comment by kzys** [comment]
I still cannot fix the issue, but I have noticed the difference between canvas-latex and our implementation (see #56).

canvas-latex's VirtualNodesToCreateJS.js is doing the following

```
function _svgNodeToCJS (node) {
  const { x, y, width, height } = node.getBounds()
  const shape = new createjs.Shape()
  const options = {
    ignoreDimensions: true,
    ignoreClear: true,
    ignoreMouse: true
  }
  shape.graphics.append({exec: (ctx) => {
    Canvg(ctx.canvas, node.virtualHtmlNode.toMarkup(), options)
  }})
  shape.setBounds(0, 0, width, height)
  shape.cache(0, 0, width, height, window.devicePixelRatio)
  shape.set({ x, y: y - height })
  return shape
}
```

However `shape.set({ x, y: y - height })` is not working on our port. I'm still unsure why.

**Comment by karino2** [comment]
I see. I think current PR get things better anyway. I merged.

Do you know why root is a little right (or number is a little left)?

**Comment by karino2** [comment]
I also check the canvas-latex code and read your comment again.
Hmm, y-height should work... I couldn't figure out why.

**Comment by kzys** [comment]
The below RNodeSpan which has pstruct and hide_tail is having `top = -3.52744em`, but according to dumpresult.txt, it has to be `-2.86722em`.

```
RNodeSpan { klasses = [], children = [RNodeSpan { klasses = [pstruct], children = [] }, RNodeSpan { klasses = [hide_tail], children = [io.github.karino2.kotlitex.RNodePathHolder@ca89670] }] }
```

I'm not 100% sure both of them should be exactly matched, but the diff is suspicious.

**Comment by karino2** [comment]
It may be because I change mode from TEXT to MATH.
I'm not sure but I wonder dumpresult.txt was created in textmode.
I'll check dump tommorow.

**Comment by karino2** [comment]
Now I use the same option as canvas-latex and update dumpresult.txt
Now, the value becomes -2.916095em, yet another value...

**Comment by karino2** [comment]
I'll investigate why this value is different. Create ticket #59.

**Comment by karino2** [comment]
You are right and the top value was wrong.
I fixed it and the result looks like below.

![normalappimage 11](https://user-images.githubusercontent.com/1468643/52898785-7b943500-3225-11e9-80c9-39cd0a16ae2e.png)

Seems better, but there is some space. Hmm.

**Comment by karino2** [comment]
When createTextNode called, the x value of setPosition seems correct (83.3 in my environment, which is direct convertion from paddingLeft=0.833em).
But when drawRenderNodes called, the value becomes 125.95.
There seems somebody move this node.

Also, there is another TextNode which text is U+200B
https://www.fileformat.info/info/unicode/char/200B/index.htm

I don't know whether this is correct or not.

**Comment by kzys** [comment]
It seems correct. The HPaddingNode before the TextNode (which has text=3) is designed to "move" the next node.

**Comment by karino2** [comment]
Then, why is there some space before 3?
Because of font difference?

When I debug execute canvas-latex, the x value of drawing time  seems the same as creation time value (36.652).
Can you guess the reason they are different?

**Comment by karino2** [comment]
Could you tell me where you move TextNode based on HPaddingNode other than creation time?

**Comment by karino2** [comment]
Reopen for a while.

**Comment by karino2** [comment]
I understand there is some other issue.
The behavior of resetState seems different from canvas-latex.
In resetState, our implementation call align()->alignCenter(), but canvas-latex does not.

**Comment by kzys** [comment]
Hmm, now I'm unsure. Regarding align(). Didn't canvas-latex do that?

https://github.com/CurriculumAssociates/canvas-latex/blob/master/src/common/virtualCanvasNodes/VerticalList.js#L82

**Comment by karino2** [comment]
It seems parentVList and vlist is the same value of different instance.
In canvas-latex, this seems the same instance.
May be some equality problem for vlist class?

**Comment by kzys** [comment]
Regarding the moving, VirtualContainerNode#setPosition is moving its children.

https://github.com/karino2/kotlitex/blob/master/app/src/main/java/io/github/karino2/kotlitex/renderer/node/VirtualCanvasNode.kt#L56

**Comment by karino2** [comment]
I guess the problem is when RenderingState.copy called, vlist is dupped.
Isn't it impossible?

**Comment by kzys** [comment]
Would it be?

https://discuss.kotlinlang.org/t/should-we-add-a-deep-copy-method-to-data-classes/9042

**Comment by karino2** [comment]
Anyway, what I observe is parentVList != vlist in our implementatoin and in canvas-latex, this check fail (not executed align() inside if block).

https://github.com/karino2/kotlitex/blob/master/app/src/main/java/io/github/karino2/kotlitex/renderer/VirtualNodeBuilder.kt#L105

**Comment by kzys** [comment]
I can check the parentVList, but I also found the difference below.

https://github.com/karino2/kotlitex/blob/master/app/src/main/java/io/github/karino2/kotlitex/renderer/RenderingState.kt#L46

https://github.com/CurriculumAssociates/canvas-latex/blob/master/src/common/RenderingState.js#L15

**Comment by karino2** [comment]
For me, our implementation seems correct. I don't know why in canvas-latex this check is fail.

**Comment by karino2** [comment]
Oh, I think you hit the point!

**Comment by karino2** [comment]
Yes! you are right! parentVlist and vlist is different in there case too but align is null and alignCenter not called.

**Comment by kzys** [comment]
The test is ongoing (#64) but can you merge #63 first?

**Comment by kzys** [comment]
Actually I probably should write real tests for #64.

**Comment by karino2** [comment]
merged.

**Comment by karino2** [comment]
Almost done (when I add some workaround for align), but width seems a little too wide (why?)

![normalappimage 12](https://user-images.githubusercontent.com/1468643/52901907-118f8600-324d-11e9-87db-86048d2f6a4b.png)

**Comment by kzys** [comment]
No idea why, but I agree it doesn't look right.
